import type { Response } from "express";
import PDFDocument from "pdfkit";
import { money, monthName } from "./utils.js";

export function streamReceiptPdf(res: Response, payment: any) {
  const doc = new PDFDocument({ size: "A4", margin: 50 });
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `inline; filename="${payment.receiptNumber}.pdf"`);
  doc.pipe(res);

  doc.fontSize(24).font("Helvetica-Bold").text(payment.property.name);
  doc.moveDown(0.2).fontSize(12).font("Helvetica").fillColor("#667085").text("Rent Payment Receipt");
  doc.fillColor("#111827").moveDown(1.5);

  const rows = [
    ["Receipt No.", payment.receiptNumber],
    ["Student", payment.student.user.fullName],
    ["Email", payment.student.user.email],
    ["Room", payment.student.room?.number || "—"],
    ["Billing Month", `${monthName(payment.invoice.month)} ${payment.invoice.year}`],
    ["Amount Paid", money(payment.amountPaise)],
    ["Payment Source", payment.source],
    ["Payment Method", payment.method || "—"],
    ["Payment Date", new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short", timeZone: payment.property.timezone }).format(payment.paidAt)],
    ["Razorpay Payment ID", payment.providerPaymentId || "—"]
  ];

  for (const [label, value] of rows) {
    doc.font("Helvetica-Bold").fontSize(11).text(label, 50, doc.y, { continued: true, width: 170 });
    doc.font("Helvetica").text(String(value));
    doc.moveDown(0.55);
  }

  doc.moveDown(1).fontSize(16).font("Helvetica-Bold").fillColor("#16A34A").text("PAID");
  doc.moveDown(1).fontSize(9).font("Helvetica").fillColor("#667085").text("This receipt was generated by SafeHouse from the payment record stored on the server.");
  doc.end();
}
